[package]
name = "index-fixed"
version = "0.0.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "Apache-2.0 OR MIT"
keywords = ["slice", "array", "const", "fixed", "index"]
repository = "https://github.com/jmesmon/index-fixed"

[dependencies]
